# Generated by Django 6.0.4 on 2026-05-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_instagrampics_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_picture', models.ImageField(blank=True, null=True, upload_to='instagram_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
