# Generated by Django 6.0.4 on 2026-05-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_ownerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerInfo',
        ),
    ]
