# Generated by Django 6.0.4 on 2026-09-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_delete_ownerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='art_description_pics/')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
