# Generated by Django 6.0.4 on 2026-09-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_instagrampics_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artdescription',
            name='description',
        ),
    ]
