# Generated by Django 6.0.1 on 2026-02-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('PAINTINGS', 'PAINTINGS'), ('CANDLES', 'CANDLES'), ('TEXTILE', 'TEXTILE')], max_length=50)),
                ('description', models.TextField()),
                ('tag', models.CharField(choices=[('GOLDEN_WOMAN ', 'GOLDEN_WOMAN '), ('SEE_COLLECTION', 'SEE_COLLECTION')], max_length=50)),
            ],
        ),
    ]
