# Generated by Django 6.0.1 on 2026-02-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_slug_collection_slug_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
