# Generated by Django 6.0.1 on 2026-02-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_collection_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
