# Generated by Django 6.0.4 on 2026-09-11 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_collection_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-published'], name='product_pro_publish_027946_idx'),
        ),
    ]
