# Generated by Django 6.0.4 on 2026-09-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_options_product_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(blank=True, null=True, upload_to='category_backgrounds/'),
        ),
    ]
