# Generated by Django 6.0.4 on 2026-09-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_name_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
